AMD:
  allocations:
  - Equities / Developed / NAM
CE31:
  allocations:
  - Bonds / Developed / Europe / Govt
CNKY:
  allocations:
  - Equities / Developed / Asia / Japan
Cash GBP:
  allocations:
  - Cash
EMIM:
  allocations:
  - Equities / EM
ERNS:
  allocations:
  - Bonds / Developed / UK / Govt
IB01:
  allocations:
  - Bonds / Developed / NAM / Govt
IBCX:
  allocations:
  - Bonds / Developed / Europe / Corp
IBGS:
  allocations:
  - Bonds / Developed / Europe / Govt
IGL5:
  allocations:
  - Bonds / Developed / UK / Govt
IGLS:
  allocations:
  - Bonds / Developed / UK / Govt
INXG:
  allocations:
  - Bonds / Developed / UK / Inflation
ISF:
  allocations:
  - Equities / Developed / EMEA / UK
ITPS:
  allocations:
  - Bonds / Developed / NAM / Inflation
IUVF:
  allocations:
  - Equities / Developed / NAM
JPEA:
  allocations:
  - Bonds / EM / Foreign / Govt
LQDA:
  allocations:
  - Bonds / Developed / NAM / Corp
MTIX:
  allocations:
  - Bonds / Developed / Europe / Inflation
NET:
  allocations:
  - Equities / Developed / NAM
SDIA:
  allocations:
  - Bonds / Developed / NAM / Corp
SEML:
  allocations:
  - Bonds / EM / Normal / Govt
SHYU:
  allocations:
  - Bonds / Developed / NAM / High Yield
SMEA:
  allocations:
  - Equities / Developed / EMEA / Non -UK
SSLN:
  allocations:
  - Alternative / Silver
SUSS:
  allocations:
  - Bonds / Developed / Europe / Corp
USTY:
  allocations:
  - Bonds / Developed / NAM / Govt
UTIP:
  allocations:
  - Bonds / Developed / NAM / Inflation
VAPX:
  allocations:
  - Equities / Developed / Asia / Ex-Japan
